[package]
name = "wordplay"
version = "0.1.0"
authors = ["Alex Gill <alex.gill@depop.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.0.0"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"